[project]
name = "replicate-idx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ipykernel>=6.29.5",
    "parquet>=1.3.1",
    "polars>=1.8.2"
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
